# Docker Compose file to run an MQTT broker and the MQTT publisher
version: '3.10'

services:

  plan:
    build:
        context: ./../../Nodes/Plan
        dockerfile: ./Dockerfile
    container_name: C_Plan

  execute:
    build:
        context: ./../../Nodes/Execute
        dockerfile: ./Dockerfile
    container_name: C_Execute


networks:
  emqx-net:
    name: emqx-net